### ISSUE TITLE
recommonmark will never support table, what can I do

### ISSUE THREAD

**Issue by leniy** [readthedocs/recommonmark#103]
I know `recommonmark` will **never** support `table` , cause this is a major feature than `markdown` , to let people to use rst.

So,is there any other `Parser` for `sphinx` to use ?

**Comment by maxgrenderjones** [comment]
Seems like a situation where AutoStructify should help - use the `eval_rst` directive to get it to output a table specified using rst format, i.e.


	```eval_rst
	+------------+------------+-----------+ 
	| Header 1   | Header 2   | Header 3  | 
	+============+============+===========+ 
	| body row 1 | column 2   | column 3  | 
	+------------+------------+-----------+ 
	| body row 2 | Cells may span columns.| 
	+------------+------------+-----------+ 
	```

**Comment by leniy** [comment]
@maxgrenderjones 
thx, and btw, how to figure out the table's boundary, cause each time I add some words to a table, I need to add lots of `----` and `====` manually.

**Comment by leniy** [comment]
Are there any automation tools?

**Comment by asmeurer** [comment]
Emacs has some tools to edit ASCII tables (https://www.gnu.org/software/emacs/manual/html_node/emacs/Text-Based-Tables.html)

But if you are just writing a simple n x m table where no cells extend beyond their width or hight, it's much easier to use a [list table](http://docutils.sourceforge.net/0.7/docs/ref/rst/directives.html#list-table) (also goes in an `eval_rst` block). 

Or, alternately, you can write the table in [pure HTML](https://www.w3schools.com/html/html_tables.asp), since Markdown supports HTML directly inline.

**Comment by aborruso** [comment]
Hi @leniy I have solved using https://github.com/ryanfox/sphinx-markdown-tables

**Comment by leniy** [comment]
@aborruso ,yes,@ryanfox 's tool is very useful.

**Comment by codejamninja** [comment]
@aborruso, (sphinx-markdown-tables)[https://github.com/ryanfox/sphinx-markdown-tables] is not true sphinx/docutils table support. It simply converts the tables to html tables. This creates major issues when writing custom sphinx builders/writers.

For example when building the [sphinx-markdown-builder](https://github.com/codejamninja/sphinx-markdown-builder), I walk the docutils tree to build markdown tables. However, this fails to work with an html table. So, I have to build a custom exception that detects html tables to convert it to a markdown table. This is certainly not ideal, because someone might explicitly define their table in html and want it kept in html. In summary, html tables should be separate from a docutils table, and recommonmark should build a docutils table from markdown tables to ensure this separation.

Sadly, the commonmark python module does not support parsing markdown tables. It has been suggested to rebuild the recommonmark parser to use the [Markdown](https://python-markdown.github.io) python module. This parser supports extensions and has a very solid extension for parsing markdown tables.

I have added the Markdown parser. It not only enables full markdown support using the [Markdown](https://python-markdown.github.io/) python module but also opens the door for more features supported by the Markdown modules various [extensions](https://python-markdown.github.io/extensions).

I have ensured the pull request is fully backward compatible with the CommonMark parser.

In order to use the Markdown parser this pull request implements, you have to explicitly set the `parser` property in the `recommonmark_config` to `Markdown`.

```py
    app.add_config_value('recommonmark_config', {
        'parser': 'Markdown'
    }, True)
```

You can see my code at the link below.
https://github.com/codejamninja/recommonmark/tree/codejamninja/python-markdown

**Comment by simonsan** [comment]
@aborruso Link worked very well! Thanks!
