### ISSUE TITLE
Label refs without `/` are assumed to be external links

### ISSUE THREAD

**Issue by gibfahn** [readthedocs/recommonmark#165]
If you have:

```markdown
[Link 1][]
[Link 2][]

[Link 1]: path/to/file:Section
[Link 2]: toplevelfile:Section
```

then `Link 1` will be parsed as an internal reference, but `Link 2` will not, this is because the URL parser thinks that `toplevelfile` is the URL scheme (like `http:` or `mailto:`) so doesn't pass it to Sphinx.

**Comment by shevron** [comment]
For anyone hitting this and still not being to work around this issue: I couldn't find it in the docs, but I had to explicitly set `known_url_schemes` in my Sphinx `conf.py` to get links like `[my link](<file1:Some Header>)` working. 

For example:

```
def setup(app):
    app.add_config_value('recommonmark_config', {
        'known_url_schemes': ['http', 'https', 'mailto'],  # <- this
        'auto_toc_tree_section': 'Contents',
    }, True)
    app.add_transform(AutoStructify)
```
Otherwise, references with no `/` were still being treated as absolute URLs.
