### ISSUE TITLE
Add syntax for admonition blocks.

### ISSUE THREAD

**Issue by drrosa** [readthedocs/recommonmark#189]
At the moment, embedding reST using `eva_rst` is the only way to render admonition blocks. It would be great to have a better syntax for admonition blocks that allows the content of admonitions to be written in Markdown and fall back reasonably on GitHub.

**Comment by noahtren** [comment]
`!!! note` seems like a pretty popular extension to Markdown for doing admonitions. See https://github.com/jupyter/notebook/issues/1292#issuecomment-477152896

It would be great if recommonmark supported this.

**Comment by noahtren** [comment]
[AutoStructify](https://recommonmark.readthedocs.io/en/latest/auto_structify.html) recommends this syntax, but it doesn't seem to work if you want an admonition with multiple lines or extra markdown formatting:
``````
``` important:: Its a note! in markdown!
```
``````

**Comment by choldgraf** [comment]
Dug into this a little bit today, just to give some extra information that I think is relevant:

The bits that over-load code cell syntax and convert them to directive syntax is in the `AutoStructify` module: https://github.com/readthedocs/recommonmark/blob/master/recommonmark/transform.py#L15

Specifically, the `auto_code_block` method uses a regex to detect in the language has the `::` syntax that is characteristic of a directive, and if so then it runs the contents of the block as a directive (https://github.com/readthedocs/recommonmark/blob/master/recommonmark/transform.py#L254). I think the issue with no multi-line syntax being supported is somewhere around here: https://github.com/readthedocs/recommonmark/blob/master/recommonmark/transform.py#L258

The other issue with that is that it's using an instance of the docutils Parser to parse the contents of the directive block, and that parser will assume that the contents are in **reStructuredText** rather than markdown, so you can't do things like:

```markdown
```note:: this [is a link](mylink.com)
```
```

**Comment by mlncn** [comment]
I support the syntax first proposed by noahtren:

```
!!! note
    This is a note.
```

This seems to be the default in the markdown in this space:

- python-markdown: https://python-markdown.github.io/extensions/admonition/
- mkdocs: https://squidfunk.github.io/mkdocs-material/extensions/admonition/

Could we plug in or use the python-mardown extension with recommonmark?

**Comment by chrisjsewell** [comment]
Note that nested parsing of Markdown is supported in https://myst-parser.readthedocs.io/en/latest/using/syntax.html#directives-a-block-level-extension-point, for admonitions any other directive, currently as:

````markdown
```{note}
This note is written in [markdown](https://example.com)
```
````

with potentially more markdown friendly syntax specific to admonitions to come: https://github.com/executablebooks/MyST-Parser/issues/154
