### ISSUE TITLE
Support tables

### ISSUE THREAD

**Issue by lu-zero** [readthedocs/recommonmark#3]
docutils has some table support, would be nice to provide a `kramdown compatible` table support.

**Comment by sid-kap** [comment]
+1

**Comment by richterb** [comment]
Agreed! Tables can be very useful when writing documentation, and when using Sphinx, it feels a bit bad to choose between writing a huge block of HTML or switching to RST just for one page.

**Comment by marcelstoer** [comment]
+1

Tables are essential for docs. If MkDocs offered better "project structuring" options (i.e. TOC options) I'd much rather use Read the Docs & MkDocs than Read the Docs & Sphinx & recommonmark. I simply don't understand why the CommonMark community is so reluctant to adopt it. It's gonna take ages until it's in CommonMark (see http://talk.commonmark.org/t/tables-in-pure-markdown/81).

**Comment by styfle** [comment]
+1

**Comment by moorchegue** [comment]
+1

**Comment by agjohnson** [comment]
My opinion on how we're using the CommonMark spec is starting to shift slightly. Personally, I'm still -1 on shoveling syntax on top of CommonMark, lest we end up with another Markdown tire fire. I do however think we could afford to prematurely adopt a CommonMark extension syntax as an experimental feature.

This would greatly improve the table authoring experience, giving authors access to docutils directives like `csv-table`[1], rather than support the authoring nightmare that is plain text tables.

I'm curious to know what authors here would think of this change compared to table syntax support.

1: http://docutils.sourceforge.net/docs/ref/rst/directives.html#id4

**Comment by nowox** [comment]
+1

**Comment by tigerhawkvok** [comment]
:+1: It was unexpected enough that this somehow isn't implemented I thought it was actually a bug at first, till I saw https://github.com/jgm/CommonMark/issues/73 . 

I think MarkdownExtra / GFM tables are better than the "table syntax support", @agjohnson -- if you're already used to Markdown, especially on most websites, using RST syntax would "break expectations", whereas implementing this would conform to expectations instead.

**Comment by agjohnson** [comment]
There's no rST required in my suggestion, it would be a Markdown extension syntax chosen from the current discussion on the commonmark spec around extensions. It's also something this module will adopt as soon as the extension spec is ratified. It wouldn't be a standard addition that other flavors/etc of markdown support, but ¯\_(ツ)_/¯ what is.

I do agree missing a table syntax would be an abrupt change for anyone more familiar with $Whatever Flavored Markdown. Perhaps table syntax could be another feature we preemptively adopt from the commonmark spec discussions as an experimental feature.

I also think most authors have varying degrees of Stockholm Syndrome when it comes to the deficiencies of authoring complex documents with markdown. Table syntax inside any markup language -- rST included -- is an utterly broken experience for authors. Docutils provides an infinitely better experience for managing large tables outside of the markup syntax. Short tables are of course better served by a native markup table syntax, though.

**Comment by marcelstoer** [comment]
> I also think most authors have varying degrees of Stockholm Syndrome when it comes to the deficiencies of authoring complex documents with markdown.

LOL, nice one :laughing: Never thought about it but associating this with Stockholm Syndrome is spot-on.

> Docutils provides an infinitely better experience for managing large tables outside of the markup syntax.

Didn't know about Docutils until you mentioned in your previous comment. I agree that probably provides a much better experience. The reason why I'd still use native markup table syntax (even if Docutils directives were available) is that those tables would render just fine when viewed on GitHub.

**Comment by brainwane** [comment]
My use case: our [Read the Docs documentation](http://zulip.readthedocs.io/) is currently a mix of reStructuredText and Markdown. We'd like to unify (as much as possible) on Markdown (zulip/zulip#668), so it's easier for people to make improvements to existing docs (since GitHub lets a user preview changes to a Markdown file in its web UI). I would like to continue to use tables for [this explanation of our directory structure](http://zulip.readthedocs.io/en/latest/directory-structure.html).

The [October 2015 announcement that Read the Docs would support Commonmark via recommonmark](https://blog.readthedocs.com/adding-markdown-support/) did say the intended usage was "basic text formatting and links" for "FAQ’s, blog posts, and other less reference heavy content" -- so if recommonmark and the CommonMark spec are not going to support tables then I'll understand.

**Comment by pfultz2** [comment]
So, I use embedded rst tables using the `eval_rst`. I wonder if for the short term, it could pass an rst table on to the `eval_rst` automatically. This might be simpler than extended commonmark to support tables.

**Comment by agjohnson** [comment]
Okay, so I believe I'll take a stab at this tomorrow. I'm proficient enough with this package and the CommonMark package, though the problem of parsing table syntaxes sounds utterly awful. The next question is this:

Do we keep CommonMark vanilla CommonMark, and instead subclass or patch the `CommonMark.Parser`, or would experimental CommonMark spec features make more sense in the `CommonMark` package?

I'll raise this question in rtfd/CommonMark-py#28 as well

**Comment by mblaettler** [comment]
What is the process regarding this issue?

I'd really like to use tables within markdown, because I intended to switch from mkdocs to sphinx and I'd like to keep most of my documentation unchanged.

I was thinking about introducing a new AutoStructify configuration to enable experimental table support. My idea would be to convert the table from Markdown to rst on the fly and pass it further to the method which evaluates inline rst.  
What would you guys think of this approach?

**Comment by marcelstoer** [comment]
Is it helpful to study the GitHub approach for hints (and maybe code)? In https://githubengineering.com/a-formal-spec-for-github-markdown/ they outlined their reasoning for forking `cmark` and then writing specific extensions (tables et.al.) in https://github.com/github/cmark/tree/master/extensions.

**Comment by mblaettler** [comment]
Thanks @marcelstoer it was an interesting read. I think such an approach would be the best option, although I'm not quite sure, how/where to implement it in this project.  
Does anybody have an idea? IMO this must be done within commonmark and not recommonmark.

I just did a proof-of-concept of my approach introduced in my previous comment, I'd be happy to get your feedback. See pull request #68 .

**Comment by agjohnson** [comment]
Yeah, i lean toward implementing this as an extension to commonmark, as some form of "experimental" extension that is likely to change. I spent some time on the commonmark spec discussion page, and think that gfm tables is probably the most accepted solution. I got stuck on actually digging through py-commonmark though, extending the parser wasn't intuitive and was going to be more than a weekend worth of work.

**Comment by q10** [comment]
What is the ETA for this feature?

**Comment by cdanger** [comment]
+1

**Comment by yishenggudou** [comment]
+1

**Comment by STRML** [comment]
While I haven't personally evaluated its correctness, it appears this was implemented in https://github.com/GovReady/CommonMark-py-Extensions. Is there any desire at RTD to get this in to support tables for their users?

**Comment by leniy** [comment]
@STRML How to use your repo in sphinx?

**Comment by ryanfox** [comment]
I wrote a sphinx extension to render tables in markdown. The source [is here.](https://github.com/ryanfox/sphinx-markdown-tables)

I uploaded it to pypi [here.](https://pypi.org/project/sphinx-markdown-tables/) It's installable via `pip install sphinx-markdown-tables`.

**Comment by leniy** [comment]
@ryanfox THX a lot

**Comment by barbara-sfx** [comment]
> I wrote a sphinx extension to render tables in markdown. The source [is here.](https://github.com/ryanfox/sphinx-markdown-tables)
> 
> I uploaded it to pypi [here.](https://pypi.org/project/sphinx-markdown-tables/) It's installable via `pip install sphinx-markdown-tables`.

Hi, and thanks. I supposedly installed it correctly....

```
Collecting sphinx-markdown-tables
  Downloading https://files.pythonhosted.org/packages/3d/d0/4f6e12f06f87bcae7a97997fc50862222ee78f859edece0da0ad75d8ada4/sphinx-markdown-tables-0.0.9.tar.gz
Collecting markdown==2.6.11 (from sphinx-markdown-tables)
  Downloading https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f5788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 4.7MB/s 
Installing collected packages: markdown, sphinx-markdown-tables
  Running setup.py install for sphinx-markdown-tables ... done
Successfully installed markdown-2.6.11 sphinx-markdown-tables-0.0.9
```

And I added it to my conf.py file:

```
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'tagging',
    'toggle',
    'newpage',
    'recommonmark',
    'sphinx-markdown-tables',
]

```

but I get this error:
Running Sphinx v1.8.2

```
Extension error:
Could not import extension sphinx-markdown-tables (exception: No module named sphinx-markdown-tables)
make: *** [html] Error 2

```

I'm far from a command-line expert. Did I miss a step somewhere? I just installed recommonmark and it seemed to work fine. 

I thought maybe I also had to add the markdown extension in conf.py, but when I did that I saw:

```
WARNING: extension 'markdown' has no setup() function; is it really a Sphinx extension module?
```

TIA

**Comment by ryanfox** [comment]
I would double check that you installed sphinx-markdown-tables to the right python environment. My guess is that sphinx can't see sphinx-markdown-tables because it got installed to (e.g.) a different virtualenv.

**Comment by barbara-sfx** [comment]
Turns out that the directory name has underlines instead of hyphens, which I didn't notice before. It is working now. Yay!

**Comment by codejamninja** [comment]
@agjohnson
@brainwane
@leniy
@lu-zero
@marcelstoer
@mblaettler
@tigerhawkvok

@aborruso, (sphinx-markdown-tables)[https://github.com/ryanfox/sphinx-markdown-tables] is not true sphinx/docutils table support. It simply converts the tables to html tables. This creates major issues when writing custom sphinx builders/writers.

For example when building the [sphinx-markdown-builder](https://github.com/codejamninja/sphinx-markdown-builder), I walk the docutils tree to build markdown tables. However, this fails to work with an html table. So, I have to build a custom exception that detects html tables to convert it to a markdown table. This is certainly not ideal, because someone might explicitly define their table in html and want it kept in html. In summary, html tables should be separate from a docutils table, and recommonmark should build a docutils table from markdown tables to ensure this separation.

Sadly, the commonmark python module does not support parsing markdown tables. It has been suggested to rebuild the recommonmark parser to use the [Markdown](https://python-markdown.github.io) python module. This parser supports extensions and has a very solid extension for parsing markdown tables.

I have created a pull request to add the Markdown parser.
#138

It not only enables full markdown support using the [Markdown](https://python-markdown.github.io/) python module but also opens the door for more features supported by the Markdown modules various [extensions](https://python-markdown.github.io/extensions).

I have ensured the pull request is fully backward compatible with the CommonMark parser.

In order to use the Markdown parser this pull request implements, you have to explicitly set the `parser` property in the `recommonmark_config` to `Markdown`.

```py
    app.add_config_value('recommonmark_config', {
        'parser': 'Markdown'
    }, True)
```

You can see my code at the link below.
https://github.com/codejamninja/recommonmark/tree/codejamninja/python-markdown

**Comment by simonsan** [comment]
This is working https://github.com/ryanfox/sphinx-markdown-tables

**Comment by soodifficult** [comment]
@ryanfox I modified conf.py referring to [here](https://github.com/ryanfox/sphinx-markdown-tables). But it still prompts me when RTD generates documents **ModuleNotFoundError: No module named 'sphinx_markdown_tables'**. Follow is my conf.py:
# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = u'InGateway'
copyright = u'2019, zhangning'
author = u'zhangning'

# The short X.Y version
version = u''
# The full version, including alpha/beta/rc tags
release = u'0.0.1'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_markdown_tables', 'recommonmark',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#

source_parsers = {
    '.md': 'recommonmark.parser.CommonMarkParser',
}
# source_suffix = ['.rst', '.md']
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = u'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

html_style = 'css/docs.css'
# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_logo = "_static/logo.png"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'InGateway doc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'InGateway.tex', u'InGateway Documentation',
     u'zhangning', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'InGateway', u'InGateway Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'InGateway', u'InGateway Documentation',
     author, 'InGateway', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']
